name: .NET

# See https://www.aaron-powell.com/posts/2020-01-10-deploying-azure-functions-with-github-actions/ for more info
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 3.1 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Publish
      run: dotnet publish --configuration Release

    - name: Upload net3.1
      uses: actions/upload-artifact@v1
      with:
          name: net3.1
          path: net31/bin/Debug/netcoreapp3.1/publish

    - name: Upload net5
      uses: actions/upload-artifact@v1
      with:
          name: net5
          path: net5/bin/Debug/netcoreapp3.1/publish
