name: .NET

# See https://www.aaron-powell.com/posts/2020-01-10-deploying-azure-functions-with-github-actions/ for more info
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 3.1 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Publish
      run: dotnet publish --configuration Release
      working-directory: src

    - name: Upload net3.1
      uses: actions/upload-artifact@v2
      with:
          name: net3.1
          path: src/net31/bin/Release/netcoreapp3.1/publish

    - name: Upload net5
      uses: actions/upload-artifact@v2
      with:
          name: net5
          path: src/net50/bin/Release/net5.0/publish

    - name: Upload net6 in-process
      uses: actions/upload-artifact@v2
      with:
          name: net6in
          path: src/net60inprocess/bin/Release/net6.0/publish

    - name: Upload net6 out-of-process
      uses: actions/upload-artifact@v2
      with:
          name: net6out
          path: src/net60outofprocess/bin/Release/net6.0/publish

  deploy:
      runs-on: ubuntu-latest
      needs: [build]

      steps:
      - name: Download net3.1
        uses: actions/download-artifact@v2
        with:
          name: net3.1
          path: net3.1

      - name: Download net5
        uses: actions/download-artifact@v2
        with:
          name: net5
          path: net5

      - name: Download net6 in-process
        uses: actions/download-artifact@v2
        with:
          name: net6in
          path: net6in

      - name: Download net6 out-of-process
        uses: actions/download-artifact@v2
        with:
          name: net6out
          path: net6out

      # Could use Azure Service Principal to log in here
      # - name: "Login via Azure CLI"
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Deploy net3.1
        uses: Azure/functions-action@v1.3.2 # Bug in v1.4 - has timeouts when deploying
        with:
            app-name: 'function-net31'
            package: net3.1
            publish-profile: ${{ secrets.PUBLISH_PROFILE_NET31 }}

      - name: Deploy net5
        uses: Azure/functions-action@v1.3.2
        with:
            app-name: 'function-net50'
            package: net5
            publish-profile: ${{ secrets.PUBLISH_PROFILE_NET50 }}

      - name: Deploy net6 in-process
        uses: Azure/functions-action@v1.3.2
        with:
            app-name: 'function-net60in'
            package: net5
            publish-profile: ${{ secrets.PUBLISH_PROFILE_NET60_IN }}

      - name: Deploy net5
        uses: Azure/functions-action@v1.3.2
        with:
            app-name: 'function-net60out'
            package: net6out
            publish-profile: ${{ secrets.PUBLISH_PROFILE_NET60_OUT }}
